[package]
name = "ball_cube_physics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.2"
bevy-inspector-egui = "0.34.0"
bevy_panorbit_camera = { version = "0.31.0", features = ["bevy_egui"] }
bevy_picking = "0.17.2"
rand = "0.9.2"
