name: Deploy Bevy WASM to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Build Bevy WASM
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Generate WASM assets
        run: wasm-bindgen --no-typescript --target web --out-dir ./out/ --out-name "ball_cube_physics" ./target/wasm32-unknown-unknown/release/ball_cube_physics.wasm

      - name: Create index.html (if not already present)
        run: cp web/index.html out/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Directory containing your WASM assets and index.html
