name: Deploy Bevy WASM to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Build Bevy WASM
        run: cargo build --target wasm32-unknown-unknown --release --features bevy_webgl2

      - name: Generate WASM assets
        run: wasm-bindgen --out-dir wasm --target web target/wasm32-unknown-unknown/release/ball_cube_physics.wasm

      - name: Create index.html (if not already present)
        run: |
          mkdir -p wasm
          cp public/index.html wasm/index.html # Adjust path to your index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wasm # Directory containing your WASM assets and index.html
